### ISSUE TITLE
Larger export from the website

### ISSUE THREAD

**Issue by j2kun** [catherinesyeh/digiweave#3]
Hi there!

I had fun tinkering with the web demo of this project (sadly I don't have the time to try out fsharp to run the code directly).

I had a large pattern that I wanted to screencap from your site, and found it a bit difficult. I had to (in chrome inspector) hide the `div id=left` element and remove the `class=left` from the output div to get a large enough image to screencap. Here was my pattern:

```
(name SERPINSKI)

(strings 32 PeachPuff PaleVioletRed PaleVioletRed PeachPuff PaleVioletRed PaleVioletRed PeachPuff PaleVioletRed PeachPuff PeachPuff PeachPuff PaleVioletRed PaleVioletRed PeachPuff PeachPuff PaleVioletRed PaleVioletRed PaleVioletRed PaleVioletRed PeachPuff PaleVioletRed PeachPuff PaleVioletRed PeachPuff PaleVioletRed PaleVioletRed PeachPuff PaleVioletRed PaleVioletRed PeachPuff PaleVioletRed PeachPuff)

A_A_A_C_A_C_A_D_A_A_A_A_A_C_A_A
_A_A_A_C_A_A_A_A_A_A_C_A_A_A_C_
D_B_D_A_A_A_A_A_A_C_A_C_A_C_B_C
_A_D_D_C_A_C_A_B_A_D_A_C_A_C_A_
A_A_C_A_A_A_B_C_A_A_C_A_A_D_C_D
_C_A_B_C_A_B_A_A_D_A_A_A_C_C_A_
A_A_C_A_A_B_B_A_A_B_A_A_C_C_A_C
_A_A_A_A_B_A_B_A_B_A_A_C_A_A_C_
D_C_C_C_B_B_B_B_B_B_B_C_A_C_C_D
_A_A_A_D_A_A_A_A_A_A_A_B_C_C_C_
D_D_C_C_A_A_A_A_A_A_C_B_B_A_A_C
_A_A_A_C_A_C_C_C_C_A_A_C_D_A_A_
B_C_B_C_D_A_B_B_B_B_B_C_C_A_A_D
_A_D_C_C_B_A_D_B_B_A_C_C_C_A_A_
A_A_A_D_D_C_A_A_B_A_A_B_B_A_A_D
_A_B_D_C_D_C_A_A_A_B_A_B_A_D_C_
A_A_A_A_A_A_A_A_B_A_A_A_A_A_B_D
```

It's a serpinski triangle, and I'd like to do a (very large) triangle start so that the entire "bracelet" is one big triangle. In case you're interested, I used a SAT solver to generate this pattern, which is also why the parts outside the triangle look strange.

Anyway, if you're still working on this project, you might want add an option to maximize the size of the output SVG in the browser window, or make it so that zooming makes it bigger.

Thanks for all the fun!

**Comment by catherinesyeh** [comment]
Hi @j2kun -- so sorry I didn't see this until now! Thank you so much for trying out digiweave and for your great suggestion. I've added the option to maximize the svg pattern now :).
